USE college;

SELECT * FROM students
ORDER BY marks ASC;

SELECT * FROM students
ORDER BY marks DESC;

SELECT * FROM students
ORDER BY age ASC;

SELECT * FROM students
ORDER BY age DESC;

SELECT * FROM students
ORDER BY name ASC;

SELECT * FROM students
ORDER BY city DESC;

SELECT name, marks
FROM students
ORDER BY marks DESC;

SELECT name, age
FROM students
ORDER BY age ASC;